-- CREATE TABLE `restroom` (
--   `idrestroom` int NOT NULL AUTO_INCREMENT,
--   `Codigo` varchar(20) DEFAULT NULL,
--   `date` date DEFAULT NULL,
--   `time` time DEFAULT NULL,
--   PRIMARY KEY (`idrestroom`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;